### ISSUE TITLE
Events class should be Kirby\Events\Events

### ISSUE THREAD

**Issue by lukasbestle** [k-next/events#3]
According to PSR-4, classes of the same package should be inside the same namespace. Having the `Events` class outside of the namespace can lead to issues if another package has the same class by accident (as currently with Kirby and the Panel).

**Comment by lukasbestle** [comment]
The `Markdown` package has the same issue (but currently only one class). We should decide now how to proceed with the namespace issue. Having sub-namespaces for everything is more verbose, but maybe better for the future. I don't know.

**Comment by bastianallgeier** [comment]
I'm torn here. I somehow hate the redundant naming but I agree that it's more standard compliant. Not sure what to do. I actually have this in many places. Another example is Structure. So it would be really good to decide now.

**Comment by distantnative** [comment]
I'm on Lukas' side here. Some problems with v2 arise from having the Panel and Kirby class outside their own namespaces. I agree that it doesn't look and feel that pretty, but I think it could really help when bringing a lot of these packages together to actually keep everything from a package in its namespace – and not leave the main class outside of it.

**Comment by lukasbestle** [comment]
As far as I can tell, this has been fixed.
